name: nephrogo
description: NephroGo.lt

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  logging: ^0.11.4
  url_launcher: ^5.7.10
  fl_chart: ^0.12.0
  package_info: ^0.4.3+2
  tuple: ^1.0.3
  equatable: ^1.2.5

  async: ^2.4.2
  stream_transform: ^1.2.0
  collection: ^1.14.13

  smooth_page_indicator: ^0.2.0

  shared_preferences: 0.5.12+4

  dio: ^3.0.10
  dio_http2_adapter: ^1.0.1
  dio_brotli_transformer: ^0.2.0

  nephrogo_api_client:
    git:
      url: https://github.com/nephrogo/nephrogo-api-dart-client.git
      ref: release/v0.2.8

  ars_progress_dialog: 0.1.2

  pretty_dio_logger: ^1.1.1

  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0+1
  firebase_messaging: ^8.0.0-dev.14

  firebase_auth: ^0.20.0+1
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.1
  flutter_facebook_auth: ^2.0.0
  sign_in_with_apple: ^2.5.4
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0
  build_runner: ^1.10.6
  flutter_launcher_icons: ^0.8.0
  test: ^1.15.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png
    - assets/logo/logo-with-title.png
    - assets/anonymous_avatar.jpg
    - assets/empty.png
    - assets/onboarding/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  adaptive_icon_background: "3F51B5"
  android: true
  ios: true
  image_path: "assets/logo/square-logo.png"